# Generated by Django 4.2.10 on 2024-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surapuradada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='managerId',
            field=models.CharField(auto_created=True, max_length=25, primary_key=True, serialize=False),
        ),
    ]
