# Generated by Django 4.2.10 on 2024-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surapuradada', '0002_alter_managers_managerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='managerId',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
