# Generated by Django 4.2.10 on 2024-07-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surapuradada', '0003_alter_managers_managerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='imagePath',
            field=models.FileField(upload_to='logos'),
        ),
    ]
