# Generated by Django 4.2.10 on 2024-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surapuradada', '0004_alter_brands_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='imagePath',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
