# Generated by Django 4.2.10 on 2024-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Surapuradada', '0005_alter_brands_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='browser',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logId',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
